---
layout: post
title:  "Welcome to Jekyll-Asciidoc!"
date:   2021-10-15 12:15:00 -0500
categories: jekyll update
---
:source-highlighter: rouge

You’ll find this post in your `_posts` directory. Go ahead and edit it and re-build the site to see your changes. You can rebuild the site in many different ways, but the most common way is to run `jekyll serve`, which launches a web server and auto-regenerates your site when a file is updated.

Jekyll requires blog post files to be named according to the following format:

`YEAR-MONTH-DAY-title.MARKUP`

Where `YEAR` is a four-digit number, `MONTH` and `DAY` are both two-digit numbers, and `MARKUP` is the file extension representing the format used in the file. After that, include the necessary front matter. Take a look at the source for this post to get an idea about how it works.

Jekyll also offers powerful support for code snippets:

[source,ruby]
----
def print_hi(name)
  puts "Hi, #{name}"
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
----

Check out the https://jekyllrb.com/docs/home[Jekyll docs] for more info on how to get the most out of Jekyll. File all bugs/feature requests at https://github.com/jekyll/jekyll[Jekyll’s GitHub repo]. If you have questions, you can ask them on https://talk.jekyllrb.com/[Jekyll Talk].